// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorData.proto

package com.rhb.rpc.protobuf.pojo;

public final class MonitorDataPojo {
  private MonitorDataPojo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MonitorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MonitorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp option = 1;</code>
     * @return Whether the option field is set.
     */
    boolean hasOption();
    /**
     * <code>.google.protobuf.Timestamp option = 1;</code>
     * @return The option.
     */
    com.google.protobuf.Timestamp getOption();
    /**
     * <code>.google.protobuf.Timestamp option = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getOptionOrBuilder();

    /**
     * <code>int64 longValue = 2;</code>
     * @return The longValue.
     */
    long getLongValue();

    /**
     * <code>string host = 3;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 3;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */
    int getTagsCount();
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */
    boolean containsTags(
        java.lang.String key);
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTags();
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTagsMap();
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    java.lang.String getTagsOrThrow(
        java.lang.String key);

    /**
     * <code>string cluster = 5;</code>
     * @return The cluster.
     */
    java.lang.String getCluster();
    /**
     * <code>string cluster = 5;</code>
     * @return The bytes for cluster.
     */
    com.google.protobuf.ByteString
        getClusterBytes();

    /**
     * <code>string routeKey = 6;</code>
     * @return The routeKey.
     */
    java.lang.String getRouteKey();
    /**
     * <code>string routeKey = 6;</code>
     * @return The bytes for routeKey.
     */
    com.google.protobuf.ByteString
        getRouteKeyBytes();

    /**
     * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
     * @return Whether the queryRequest field is set.
     */
    boolean hasQueryRequest();
    /**
     * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
     * @return The queryRequest.
     */
    com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest getQueryRequest();
    /**
     * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
     */
    com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequestOrBuilder getQueryRequestOrBuilder();

    /**
     * <code>.MonitorData.RunStatus runStatus = 8;</code>
     * @return The enum numeric value on the wire for runStatus.
     */
    int getRunStatusValue();
    /**
     * <code>.MonitorData.RunStatus runStatus = 8;</code>
     * @return The runStatus.
     */
    com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus getRunStatus();
  }
  /**
   * Protobuf type {@code MonitorData}
   */
  public static final class MonitorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MonitorData)
      MonitorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MonitorData.newBuilder() to construct.
    private MonitorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MonitorData() {
      host_ = "";
      cluster_ = "";
      routeKey_ = "";
      runStatus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MonitorData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MonitorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (option_ != null) {
                subBuilder = option_.toBuilder();
              }
              option_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(option_);
                option_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              longValue_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tags_ = com.google.protobuf.MapField.newMapField(
                    TagsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tags__ = input.readMessage(
                  TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              tags_.getMutableMap().put(
                  tags__.getKey(), tags__.getValue());
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              cluster_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              routeKey_ = s;
              break;
            }
            case 58: {
              com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder subBuilder = null;
              if (queryRequest_ != null) {
                subBuilder = queryRequest_.toBuilder();
              }
              queryRequest_ = input.readMessage(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(queryRequest_);
                queryRequest_ = subBuilder.buildPartial();
              }

              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              runStatus_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.class, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.Builder.class);
    }

    /**
     * Protobuf enum {@code MonitorData.RunStatus}
     */
    public enum RunStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOW = 0;</code>
       */
      UNKNOW(0),
      /**
       * <code>RUNNING = 1;</code>
       */
      RUNNING(1),
      /**
       * <code>STOP = 2;</code>
       */
      STOP(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOW = 0;</code>
       */
      public static final int UNKNOW_VALUE = 0;
      /**
       * <code>RUNNING = 1;</code>
       */
      public static final int RUNNING_VALUE = 1;
      /**
       * <code>STOP = 2;</code>
       */
      public static final int STOP_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RunStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RunStatus forNumber(int value) {
        switch (value) {
          case 0: return UNKNOW;
          case 1: return RUNNING;
          case 2: return STOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RunStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RunStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RunStatus>() {
              public RunStatus findValueByNumber(int number) {
                return RunStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.getDescriptor().getEnumTypes().get(0);
      }

      private static final RunStatus[] VALUES = values();

      public static RunStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RunStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MonitorData.RunStatus)
    }

    public interface QueryRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MonitorData.QueryRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string queryField = 1;</code>
       * @return The queryField.
       */
      java.lang.String getQueryField();
      /**
       * <code>string queryField = 1;</code>
       * @return The bytes for queryField.
       */
      com.google.protobuf.ByteString
          getQueryFieldBytes();

      /**
       * <code>string queryValue = 2;</code>
       * @return The queryValue.
       */
      java.lang.String getQueryValue();
      /**
       * <code>string queryValue = 2;</code>
       * @return The bytes for queryValue.
       */
      com.google.protobuf.ByteString
          getQueryValueBytes();

      /**
       * <code>double score = 3;</code>
       * @return The score.
       */
      double getScore();

      /**
       * <code>bool isLike = 4;</code>
       * @return The isLike.
       */
      boolean getIsLike();
    }
    /**
     * Protobuf type {@code MonitorData.QueryRequest}
     */
    public static final class QueryRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MonitorData.QueryRequest)
        QueryRequestOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use QueryRequest.newBuilder() to construct.
      private QueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private QueryRequest() {
        queryField_ = "";
        queryValue_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new QueryRequest();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private QueryRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                queryField_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                queryValue_ = s;
                break;
              }
              case 25: {

                score_ = input.readDouble();
                break;
              }
              case 32: {

                isLike_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_QueryRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_QueryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.class, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder.class);
      }

      public static final int QUERYFIELD_FIELD_NUMBER = 1;
      private volatile java.lang.Object queryField_;
      /**
       * <code>string queryField = 1;</code>
       * @return The queryField.
       */
      @java.lang.Override
      public java.lang.String getQueryField() {
        java.lang.Object ref = queryField_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          queryField_ = s;
          return s;
        }
      }
      /**
       * <code>string queryField = 1;</code>
       * @return The bytes for queryField.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getQueryFieldBytes() {
        java.lang.Object ref = queryField_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queryField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int QUERYVALUE_FIELD_NUMBER = 2;
      private volatile java.lang.Object queryValue_;
      /**
       * <code>string queryValue = 2;</code>
       * @return The queryValue.
       */
      @java.lang.Override
      public java.lang.String getQueryValue() {
        java.lang.Object ref = queryValue_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          queryValue_ = s;
          return s;
        }
      }
      /**
       * <code>string queryValue = 2;</code>
       * @return The bytes for queryValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getQueryValueBytes() {
        java.lang.Object ref = queryValue_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queryValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SCORE_FIELD_NUMBER = 3;
      private double score_;
      /**
       * <code>double score = 3;</code>
       * @return The score.
       */
      @java.lang.Override
      public double getScore() {
        return score_;
      }

      public static final int ISLIKE_FIELD_NUMBER = 4;
      private boolean isLike_;
      /**
       * <code>bool isLike = 4;</code>
       * @return The isLike.
       */
      @java.lang.Override
      public boolean getIsLike() {
        return isLike_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getQueryFieldBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, queryField_);
        }
        if (!getQueryValueBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, queryValue_);
        }
        if (score_ != 0D) {
          output.writeDouble(3, score_);
        }
        if (isLike_ != false) {
          output.writeBool(4, isLike_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getQueryFieldBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, queryField_);
        }
        if (!getQueryValueBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, queryValue_);
        }
        if (score_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, score_);
        }
        if (isLike_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(4, isLike_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest)) {
          return super.equals(obj);
        }
        com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest other = (com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest) obj;

        if (!getQueryField()
            .equals(other.getQueryField())) return false;
        if (!getQueryValue()
            .equals(other.getQueryValue())) return false;
        if (java.lang.Double.doubleToLongBits(getScore())
            != java.lang.Double.doubleToLongBits(
                other.getScore())) return false;
        if (getIsLike()
            != other.getIsLike()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + QUERYFIELD_FIELD_NUMBER;
        hash = (53 * hash) + getQueryField().hashCode();
        hash = (37 * hash) + QUERYVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getQueryValue().hashCode();
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getScore()));
        hash = (37 * hash) + ISLIKE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsLike());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MonitorData.QueryRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MonitorData.QueryRequest)
          com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_QueryRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_QueryRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.class, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder.class);
        }

        // Construct using com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          queryField_ = "";

          queryValue_ = "";

          score_ = 0D;

          isLike_ = false;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_QueryRequest_descriptor;
        }

        @java.lang.Override
        public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest getDefaultInstanceForType() {
          return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest build() {
          com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest buildPartial() {
          com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest result = new com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest(this);
          result.queryField_ = queryField_;
          result.queryValue_ = queryValue_;
          result.score_ = score_;
          result.isLike_ = isLike_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest) {
            return mergeFrom((com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest other) {
          if (other == com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.getDefaultInstance()) return this;
          if (!other.getQueryField().isEmpty()) {
            queryField_ = other.queryField_;
            onChanged();
          }
          if (!other.getQueryValue().isEmpty()) {
            queryValue_ = other.queryValue_;
            onChanged();
          }
          if (other.getScore() != 0D) {
            setScore(other.getScore());
          }
          if (other.getIsLike() != false) {
            setIsLike(other.getIsLike());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object queryField_ = "";
        /**
         * <code>string queryField = 1;</code>
         * @return The queryField.
         */
        public java.lang.String getQueryField() {
          java.lang.Object ref = queryField_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            queryField_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string queryField = 1;</code>
         * @return The bytes for queryField.
         */
        public com.google.protobuf.ByteString
            getQueryFieldBytes() {
          java.lang.Object ref = queryField_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            queryField_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string queryField = 1;</code>
         * @param value The queryField to set.
         * @return This builder for chaining.
         */
        public Builder setQueryField(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          queryField_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string queryField = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearQueryField() {
          
          queryField_ = getDefaultInstance().getQueryField();
          onChanged();
          return this;
        }
        /**
         * <code>string queryField = 1;</code>
         * @param value The bytes for queryField to set.
         * @return This builder for chaining.
         */
        public Builder setQueryFieldBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          queryField_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object queryValue_ = "";
        /**
         * <code>string queryValue = 2;</code>
         * @return The queryValue.
         */
        public java.lang.String getQueryValue() {
          java.lang.Object ref = queryValue_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            queryValue_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string queryValue = 2;</code>
         * @return The bytes for queryValue.
         */
        public com.google.protobuf.ByteString
            getQueryValueBytes() {
          java.lang.Object ref = queryValue_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            queryValue_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string queryValue = 2;</code>
         * @param value The queryValue to set.
         * @return This builder for chaining.
         */
        public Builder setQueryValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          queryValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string queryValue = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearQueryValue() {
          
          queryValue_ = getDefaultInstance().getQueryValue();
          onChanged();
          return this;
        }
        /**
         * <code>string queryValue = 2;</code>
         * @param value The bytes for queryValue to set.
         * @return This builder for chaining.
         */
        public Builder setQueryValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          queryValue_ = value;
          onChanged();
          return this;
        }

        private double score_ ;
        /**
         * <code>double score = 3;</code>
         * @return The score.
         */
        @java.lang.Override
        public double getScore() {
          return score_;
        }
        /**
         * <code>double score = 3;</code>
         * @param value The score to set.
         * @return This builder for chaining.
         */
        public Builder setScore(double value) {
          
          score_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double score = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearScore() {
          
          score_ = 0D;
          onChanged();
          return this;
        }

        private boolean isLike_ ;
        /**
         * <code>bool isLike = 4;</code>
         * @return The isLike.
         */
        @java.lang.Override
        public boolean getIsLike() {
          return isLike_;
        }
        /**
         * <code>bool isLike = 4;</code>
         * @param value The isLike to set.
         * @return This builder for chaining.
         */
        public Builder setIsLike(boolean value) {
          
          isLike_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool isLike = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearIsLike() {
          
          isLike_ = false;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MonitorData.QueryRequest)
      }

      // @@protoc_insertion_point(class_scope:MonitorData.QueryRequest)
      private static final com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest();
      }

      public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<QueryRequest>
          PARSER = new com.google.protobuf.AbstractParser<QueryRequest>() {
        @java.lang.Override
        public QueryRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryRequest(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<QueryRequest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<QueryRequest> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int OPTION_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp option_;
    /**
     * <code>.google.protobuf.Timestamp option = 1;</code>
     * @return Whether the option field is set.
     */
    @java.lang.Override
    public boolean hasOption() {
      return option_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp option = 1;</code>
     * @return The option.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getOption() {
      return option_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : option_;
    }
    /**
     * <code>.google.protobuf.Timestamp option = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getOptionOrBuilder() {
      return getOption();
    }

    public static final int LONGVALUE_FIELD_NUMBER = 2;
    private long longValue_;
    /**
     * <code>int64 longValue = 2;</code>
     * @return The longValue.
     */
    @java.lang.Override
    public long getLongValue() {
      return longValue_;
    }

    public static final int HOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 3;</code>
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 3;</code>
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 4;
    private static final class TagsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_TagsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    @java.lang.Override
    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int CLUSTER_FIELD_NUMBER = 5;
    private volatile java.lang.Object cluster_;
    /**
     * <code>string cluster = 5;</code>
     * @return The cluster.
     */
    @java.lang.Override
    public java.lang.String getCluster() {
      java.lang.Object ref = cluster_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      }
    }
    /**
     * <code>string cluster = 5;</code>
     * @return The bytes for cluster.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTEKEY_FIELD_NUMBER = 6;
    private volatile java.lang.Object routeKey_;
    /**
     * <code>string routeKey = 6;</code>
     * @return The routeKey.
     */
    @java.lang.Override
    public java.lang.String getRouteKey() {
      java.lang.Object ref = routeKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routeKey_ = s;
        return s;
      }
    }
    /**
     * <code>string routeKey = 6;</code>
     * @return The bytes for routeKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRouteKeyBytes() {
      java.lang.Object ref = routeKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routeKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERYREQUEST_FIELD_NUMBER = 7;
    private com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest queryRequest_;
    /**
     * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
     * @return Whether the queryRequest field is set.
     */
    @java.lang.Override
    public boolean hasQueryRequest() {
      return queryRequest_ != null;
    }
    /**
     * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
     * @return The queryRequest.
     */
    @java.lang.Override
    public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest getQueryRequest() {
      return queryRequest_ == null ? com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.getDefaultInstance() : queryRequest_;
    }
    /**
     * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
     */
    @java.lang.Override
    public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequestOrBuilder getQueryRequestOrBuilder() {
      return getQueryRequest();
    }

    public static final int RUNSTATUS_FIELD_NUMBER = 8;
    private int runStatus_;
    /**
     * <code>.MonitorData.RunStatus runStatus = 8;</code>
     * @return The enum numeric value on the wire for runStatus.
     */
    @java.lang.Override public int getRunStatusValue() {
      return runStatus_;
    }
    /**
     * <code>.MonitorData.RunStatus runStatus = 8;</code>
     * @return The runStatus.
     */
    @java.lang.Override public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus getRunStatus() {
      @SuppressWarnings("deprecation")
      com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus result = com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus.valueOf(runStatus_);
      return result == null ? com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (option_ != null) {
        output.writeMessage(1, getOption());
      }
      if (longValue_ != 0L) {
        output.writeInt64(2, longValue_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, host_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTags(),
          TagsDefaultEntryHolder.defaultEntry,
          4);
      if (!getClusterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cluster_);
      }
      if (!getRouteKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, routeKey_);
      }
      if (queryRequest_ != null) {
        output.writeMessage(7, getQueryRequest());
      }
      if (runStatus_ != com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus.UNKNOW.getNumber()) {
        output.writeEnum(8, runStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (option_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOption());
      }
      if (longValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longValue_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, host_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTags().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, tags__);
      }
      if (!getClusterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cluster_);
      }
      if (!getRouteKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, routeKey_);
      }
      if (queryRequest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getQueryRequest());
      }
      if (runStatus_ != com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus.UNKNOW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, runStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData)) {
        return super.equals(obj);
      }
      com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData other = (com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData) obj;

      if (hasOption() != other.hasOption()) return false;
      if (hasOption()) {
        if (!getOption()
            .equals(other.getOption())) return false;
      }
      if (getLongValue()
          != other.getLongValue()) return false;
      if (!getHost()
          .equals(other.getHost())) return false;
      if (!internalGetTags().equals(
          other.internalGetTags())) return false;
      if (!getCluster()
          .equals(other.getCluster())) return false;
      if (!getRouteKey()
          .equals(other.getRouteKey())) return false;
      if (hasQueryRequest() != other.hasQueryRequest()) return false;
      if (hasQueryRequest()) {
        if (!getQueryRequest()
            .equals(other.getQueryRequest())) return false;
      }
      if (runStatus_ != other.runStatus_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOption()) {
        hash = (37 * hash) + OPTION_FIELD_NUMBER;
        hash = (53 * hash) + getOption().hashCode();
      }
      hash = (37 * hash) + LONGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongValue());
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      if (!internalGetTags().getMap().isEmpty()) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTags().hashCode();
      }
      hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
      hash = (53 * hash) + getCluster().hashCode();
      hash = (37 * hash) + ROUTEKEY_FIELD_NUMBER;
      hash = (53 * hash) + getRouteKey().hashCode();
      if (hasQueryRequest()) {
        hash = (37 * hash) + QUERYREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getQueryRequest().hashCode();
      }
      hash = (37 * hash) + RUNSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + runStatus_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MonitorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MonitorData)
        com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.class, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.Builder.class);
      }

      // Construct using com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (optionBuilder_ == null) {
          option_ = null;
        } else {
          option_ = null;
          optionBuilder_ = null;
        }
        longValue_ = 0L;

        host_ = "";

        internalGetMutableTags().clear();
        cluster_ = "";

        routeKey_ = "";

        if (queryRequestBuilder_ == null) {
          queryRequest_ = null;
        } else {
          queryRequest_ = null;
          queryRequestBuilder_ = null;
        }
        runStatus_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.internal_static_MonitorData_descriptor;
      }

      @java.lang.Override
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData getDefaultInstanceForType() {
        return com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.getDefaultInstance();
      }

      @java.lang.Override
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData build() {
        com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData buildPartial() {
        com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData result = new com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData(this);
        int from_bitField0_ = bitField0_;
        if (optionBuilder_ == null) {
          result.option_ = option_;
        } else {
          result.option_ = optionBuilder_.build();
        }
        result.longValue_ = longValue_;
        result.host_ = host_;
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
        result.cluster_ = cluster_;
        result.routeKey_ = routeKey_;
        if (queryRequestBuilder_ == null) {
          result.queryRequest_ = queryRequest_;
        } else {
          result.queryRequest_ = queryRequestBuilder_.build();
        }
        result.runStatus_ = runStatus_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData) {
          return mergeFrom((com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData other) {
        if (other == com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.getDefaultInstance()) return this;
        if (other.hasOption()) {
          mergeOption(other.getOption());
        }
        if (other.getLongValue() != 0L) {
          setLongValue(other.getLongValue());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        internalGetMutableTags().mergeFrom(
            other.internalGetTags());
        if (!other.getCluster().isEmpty()) {
          cluster_ = other.cluster_;
          onChanged();
        }
        if (!other.getRouteKey().isEmpty()) {
          routeKey_ = other.routeKey_;
          onChanged();
        }
        if (other.hasQueryRequest()) {
          mergeQueryRequest(other.getQueryRequest());
        }
        if (other.runStatus_ != 0) {
          setRunStatusValue(other.getRunStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp option_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> optionBuilder_;
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       * @return Whether the option field is set.
       */
      public boolean hasOption() {
        return optionBuilder_ != null || option_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       * @return The option.
       */
      public com.google.protobuf.Timestamp getOption() {
        if (optionBuilder_ == null) {
          return option_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : option_;
        } else {
          return optionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       */
      public Builder setOption(com.google.protobuf.Timestamp value) {
        if (optionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          option_ = value;
          onChanged();
        } else {
          optionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       */
      public Builder setOption(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (optionBuilder_ == null) {
          option_ = builderForValue.build();
          onChanged();
        } else {
          optionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       */
      public Builder mergeOption(com.google.protobuf.Timestamp value) {
        if (optionBuilder_ == null) {
          if (option_ != null) {
            option_ =
              com.google.protobuf.Timestamp.newBuilder(option_).mergeFrom(value).buildPartial();
          } else {
            option_ = value;
          }
          onChanged();
        } else {
          optionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       */
      public Builder clearOption() {
        if (optionBuilder_ == null) {
          option_ = null;
          onChanged();
        } else {
          option_ = null;
          optionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getOptionBuilder() {
        
        onChanged();
        return getOptionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getOptionOrBuilder() {
        if (optionBuilder_ != null) {
          return optionBuilder_.getMessageOrBuilder();
        } else {
          return option_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : option_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp option = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getOptionFieldBuilder() {
        if (optionBuilder_ == null) {
          optionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getOption(),
                  getParentForChildren(),
                  isClean());
          option_ = null;
        }
        return optionBuilder_;
      }

      private long longValue_ ;
      /**
       * <code>int64 longValue = 2;</code>
       * @return The longValue.
       */
      @java.lang.Override
      public long getLongValue() {
        return longValue_;
      }
      /**
       * <code>int64 longValue = 2;</code>
       * @param value The longValue to set.
       * @return This builder for chaining.
       */
      public Builder setLongValue(long value) {
        
        longValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongValue() {
        
        longValue_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 3;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 3;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 3;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 3;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> tags_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTags() {
        if (tags_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        return tags_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTags() {
        onChanged();;
        if (tags_ == null) {
          tags_ = com.google.protobuf.MapField.newMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        if (!tags_.isMutable()) {
          tags_ = tags_.copy();
        }
        return tags_;
      }

      public int getTagsCount() {
        return internalGetTags().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 4;</code>
       */

      @java.lang.Override
      public boolean containsTags(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTags().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTagsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTags() {
        return getTagsMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 4;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
        return internalGetTags().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getTagsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getTagsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTags() {
        internalGetMutableTags().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 4;</code>
       */

      public Builder removeTags(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTags().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTags() {
        return internalGetMutableTags().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 4;</code>
       */
      public Builder putTags(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTags().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 4;</code>
       */

      public Builder putAllTags(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableTags().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object cluster_ = "";
      /**
       * <code>string cluster = 5;</code>
       * @return The cluster.
       */
      public java.lang.String getCluster() {
        java.lang.Object ref = cluster_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cluster_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cluster = 5;</code>
       * @return The bytes for cluster.
       */
      public com.google.protobuf.ByteString
          getClusterBytes() {
        java.lang.Object ref = cluster_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cluster_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cluster = 5;</code>
       * @param value The cluster to set.
       * @return This builder for chaining.
       */
      public Builder setCluster(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cluster_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cluster = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCluster() {
        
        cluster_ = getDefaultInstance().getCluster();
        onChanged();
        return this;
      }
      /**
       * <code>string cluster = 5;</code>
       * @param value The bytes for cluster to set.
       * @return This builder for chaining.
       */
      public Builder setClusterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cluster_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object routeKey_ = "";
      /**
       * <code>string routeKey = 6;</code>
       * @return The routeKey.
       */
      public java.lang.String getRouteKey() {
        java.lang.Object ref = routeKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          routeKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string routeKey = 6;</code>
       * @return The bytes for routeKey.
       */
      public com.google.protobuf.ByteString
          getRouteKeyBytes() {
        java.lang.Object ref = routeKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routeKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string routeKey = 6;</code>
       * @param value The routeKey to set.
       * @return This builder for chaining.
       */
      public Builder setRouteKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        routeKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string routeKey = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRouteKey() {
        
        routeKey_ = getDefaultInstance().getRouteKey();
        onChanged();
        return this;
      }
      /**
       * <code>string routeKey = 6;</code>
       * @param value The bytes for routeKey to set.
       * @return This builder for chaining.
       */
      public Builder setRouteKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        routeKey_ = value;
        onChanged();
        return this;
      }

      private com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest queryRequest_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequestOrBuilder> queryRequestBuilder_;
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       * @return Whether the queryRequest field is set.
       */
      public boolean hasQueryRequest() {
        return queryRequestBuilder_ != null || queryRequest_ != null;
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       * @return The queryRequest.
       */
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest getQueryRequest() {
        if (queryRequestBuilder_ == null) {
          return queryRequest_ == null ? com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.getDefaultInstance() : queryRequest_;
        } else {
          return queryRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       */
      public Builder setQueryRequest(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest value) {
        if (queryRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          queryRequest_ = value;
          onChanged();
        } else {
          queryRequestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       */
      public Builder setQueryRequest(
          com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder builderForValue) {
        if (queryRequestBuilder_ == null) {
          queryRequest_ = builderForValue.build();
          onChanged();
        } else {
          queryRequestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       */
      public Builder mergeQueryRequest(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest value) {
        if (queryRequestBuilder_ == null) {
          if (queryRequest_ != null) {
            queryRequest_ =
              com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.newBuilder(queryRequest_).mergeFrom(value).buildPartial();
          } else {
            queryRequest_ = value;
          }
          onChanged();
        } else {
          queryRequestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       */
      public Builder clearQueryRequest() {
        if (queryRequestBuilder_ == null) {
          queryRequest_ = null;
          onChanged();
        } else {
          queryRequest_ = null;
          queryRequestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       */
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder getQueryRequestBuilder() {
        
        onChanged();
        return getQueryRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       */
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequestOrBuilder getQueryRequestOrBuilder() {
        if (queryRequestBuilder_ != null) {
          return queryRequestBuilder_.getMessageOrBuilder();
        } else {
          return queryRequest_ == null ?
              com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.getDefaultInstance() : queryRequest_;
        }
      }
      /**
       * <code>.MonitorData.QueryRequest queryRequest = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequestOrBuilder> 
          getQueryRequestFieldBuilder() {
        if (queryRequestBuilder_ == null) {
          queryRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequest.Builder, com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.QueryRequestOrBuilder>(
                  getQueryRequest(),
                  getParentForChildren(),
                  isClean());
          queryRequest_ = null;
        }
        return queryRequestBuilder_;
      }

      private int runStatus_ = 0;
      /**
       * <code>.MonitorData.RunStatus runStatus = 8;</code>
       * @return The enum numeric value on the wire for runStatus.
       */
      @java.lang.Override public int getRunStatusValue() {
        return runStatus_;
      }
      /**
       * <code>.MonitorData.RunStatus runStatus = 8;</code>
       * @param value The enum numeric value on the wire for runStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRunStatusValue(int value) {
        
        runStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MonitorData.RunStatus runStatus = 8;</code>
       * @return The runStatus.
       */
      @java.lang.Override
      public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus getRunStatus() {
        @SuppressWarnings("deprecation")
        com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus result = com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus.valueOf(runStatus_);
        return result == null ? com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.MonitorData.RunStatus runStatus = 8;</code>
       * @param value The runStatus to set.
       * @return This builder for chaining.
       */
      public Builder setRunStatus(com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData.RunStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        runStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MonitorData.RunStatus runStatus = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRunStatus() {
        
        runStatus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MonitorData)
    }

    // @@protoc_insertion_point(class_scope:MonitorData)
    private static final com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData();
    }

    public static com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MonitorData>
        PARSER = new com.google.protobuf.AbstractParser<MonitorData>() {
      @java.lang.Override
      public MonitorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MonitorData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MonitorData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MonitorData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rhb.rpc.protobuf.pojo.MonitorDataPojo.MonitorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitorData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitorData_TagsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitorData_TagsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MonitorData_QueryRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MonitorData_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MonitorData.proto\032\037google/protobuf/tim" +
      "estamp.proto\"\263\003\n\013MonitorData\022*\n\006option\030\001" +
      " \001(\0132\032.google.protobuf.Timestamp\022\021\n\tlong" +
      "Value\030\002 \001(\003\022\014\n\004host\030\003 \001(\t\022$\n\004tags\030\004 \003(\0132" +
      "\026.MonitorData.TagsEntry\022\017\n\007cluster\030\005 \001(\t" +
      "\022\020\n\010routeKey\030\006 \001(\t\022/\n\014queryRequest\030\007 \001(\013" +
      "2\031.MonitorData.QueryRequest\022)\n\trunStatus" +
      "\030\010 \001(\0162\026.MonitorData.RunStatus\032+\n\tTagsEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032U\n\014Q" +
      "ueryRequest\022\022\n\nqueryField\030\001 \001(\t\022\022\n\nquery" +
      "Value\030\002 \001(\t\022\r\n\005score\030\003 \001(\001\022\016\n\006isLike\030\004 \001" +
      "(\010\".\n\tRunStatus\022\n\n\006UNKNOW\020\000\022\013\n\007RUNNING\020\001" +
      "\022\010\n\004STOP\020\002B,\n\031com.rhb.rpc.protobuf.pojoB" +
      "\017MonitorDataPojoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_MonitorData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MonitorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitorData_descriptor,
        new java.lang.String[] { "Option", "LongValue", "Host", "Tags", "Cluster", "RouteKey", "QueryRequest", "RunStatus", });
    internal_static_MonitorData_TagsEntry_descriptor =
      internal_static_MonitorData_descriptor.getNestedTypes().get(0);
    internal_static_MonitorData_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitorData_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_MonitorData_QueryRequest_descriptor =
      internal_static_MonitorData_descriptor.getNestedTypes().get(1);
    internal_static_MonitorData_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MonitorData_QueryRequest_descriptor,
        new java.lang.String[] { "QueryField", "QueryValue", "Score", "IsLike", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
